const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={token:localStorage.getItem('ghan_token')||'',user:null,vault:[],quiz:null};
function toast(msg,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;$('#toast').appendChild(el);setTimeout(()=>el.remove(),3200)}
const API_BASE=String(window.GHAN_API_URL||'').replace(/\/$/,'');
async function api(url,opts={}){url=`${API_BASE}${url}`;opts.headers={...(opts.headers||{}),...(state.token?{Authorization:`Bearer ${state.token}`}:{})};const r=await fetch(url,opts);let data={};try{data=await r.json()}catch{}if(r.status===401){logout(false);throw new Error(data.error||'Sesi berakhir.')}if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function applyTheme(theme){document.body.classList.toggle('dark',theme==='dark');$('#themeToggle').textContent=theme==='dark'?'☀':'☾';if(state.user)state.user.theme=theme;localStorage.setItem('ghan_theme',theme)}
function setAuth(mode){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.auth===mode));$('#loginForm').classList.toggle('hidden',mode!=='login');$('#registerForm').classList.toggle('hidden',mode!=='register');$('#authMsg').textContent=''}
$$('.tab').forEach(b=>b.onclick=()=>setAuth(b.dataset.auth));
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identity:$('#loginIdentity').value,password:$('#loginPassword').value})});loginDone(d)}catch(e){$('#authMsg').textContent=e.message}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#regUsername').value,email:$('#regEmail').value,password:$('#regPassword').value})});loginDone(d)}catch(e){$('#authMsg').textContent=e.message}};
function loginDone(d){state.token=d.token;state.user=d.user;localStorage.setItem('ghan_token',d.token);localStorage.setItem('ghan_theme',d.user.theme||'light');applyTheme(d.user.theme||'light');$('#authScreen').classList.add('hidden');$('#app').classList.remove('hidden');renderUser();loadDashboard()}
async function boot(){applyTheme(localStorage.getItem('ghan_theme')||'light');if(!state.token)return;try{const d=await api('/api/me');state.user=d.user;$('#authScreen').classList.add('hidden');$('#app').classList.remove('hidden');renderUser();loadDashboard()}catch{}}
function renderUser(){const u=state.user;if(!u)return;$('#dashName').textContent=u.name||u.username;$('#profileName').value=u.name||'';$('#profileUsername').value=u.username;$('#profileEmail').value=u.email||'';$('#profileBio').value=u.bio||'';$('#profileTheme').value=u.theme||'light';setAvatar($('#avatarBtn'),u);setAvatar($('#profileAvatar'),u)}
function setAvatar(el,u){if(!el)return;if(u.avatar){el.innerHTML=`<img src="${API_BASE}${u.avatar}" alt="avatar">`}else el.textContent=(u.name||u.username||'G')[0].toUpperCase()}
function logout(show=true){state.token='';state.user=null;localStorage.removeItem('ghan_token');$('#app').classList.add('hidden');$('#authScreen').classList.remove('hidden');if(show)toast('Kamu sudah keluar')}
$('#logout').onclick=()=>logout();$('#avatarBtn').onclick=()=>showPage('profile');
function showPage(name){$$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${name}`));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===name));const titles={dashboard:'Dashboard',solve:'Problem Solver',summary:'Ringkasan Materi',quiz:'Kuis Interaktif',tutor:'AI Study Tutor',vault:'Vault Materi',streak:'Daily Streak',profile:'Edit Profile',support:'Customer Service'};$('#pageTitle').textContent=titles[name]||name;$('#pageKicker').textContent=name==='dashboard'?'RUANG BELAJAR':name.toUpperCase();$('#app .sidebar').classList.remove('open');$('#scrim').classList.remove('show')}
$$('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('#menuBtn').onclick=()=>{$('#app .sidebar').classList.add('open');$('#scrim').classList.add('show')};$('#closeSide').onclick=()=>{$('#app .sidebar').classList.remove('open');$('#scrim').classList.remove('show')};$('#scrim').onclick=()=>{$('#app .sidebar').classList.remove('open');$('#scrim').classList.remove('show')};
$('#themeToggle').onclick=async()=>{const t=document.body.classList.contains('dark')?'light':'dark';applyTheme(t);if(state.token)await saveProfile({theme:t},false)};
async function loadDashboard(){try{const d=await api('/api/dashboard');$('#statStreak').textContent=d.streak;$('#statMaterials').textContent=d.materials;$('#statToday').textContent=d.today?'Sudah ✓':'Belum';$('#streakBig').textContent=`${d.streak} hari`;$('#recent').innerHTML=d.recent.length?d.recent.map(x=>`<div class="recent-item"><div><b>${esc(x.title)}</b><small>${esc(x.subject||'Umum')} ${x.attachment?.name?'• 📎 '+esc(x.attachment.name):''}</small></div><button class="link-btn" onclick="openVault('${x.id}')">Buka</button></div>`).join(''):'<div class="recent-item"><span>Belum ada materi.</span><button class="link-btn" onclick="showPage(\'vault\')">Tambah</button></div>'}catch(e){toast(e.message,'bad')}loadVault();loadStreak()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function extract(file){const fd=new FormData();fd.append('file',file);return (await api('/api/extract-file',{method:'POST',body:fd})).text}
async function tool(tool,text,file,out){try{out.textContent='Memproses...';let source='';if(file)source=await extract(file);const d=await api(`/api/ai/${tool}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,sourceText:source})});out.textContent=d.text;toast(`Berhasil • ${d.provider==='gemini'?'Gemini backup':'AI utama'}`,'good')}catch(e){out.textContent='';toast(e.message,'bad')}}
$('#solveBtn').onclick=()=>tool('solve',$('#solveText').value,$('#solveFile').files[0],$('#solveOut'));
$('#summaryBtn').onclick=()=>tool('summary',$('#summaryText').value,$('#summaryFile').files[0],$('#summaryOut'));
$('#tutorBtn').onclick=async()=>{const text=$('#tutorText').value.trim();if(!text)return;addBubble(text,'user');$('#tutorText').value='';try{let source='';if($('#tutorFile').files[0])source=await extract($('#tutorFile').files[0]);const d=await api('/api/ai/tutor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,sourceText:source})});addBubble(d.text,'ai')}catch(e){addBubble(e.message,'ai')}};
function addBubble(t,type){const b=document.createElement('div');b.className=`bubble ${type}`;b.textContent=t;$('#chat').appendChild(b);$('#chat').scrollTop=$('#chat').scrollHeight}
$('#tutorText').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#tutorBtn').click()}});
const quizFile=$('#quizFile');
quizFile?.addEventListener('change',()=>{const f=quizFile.files[0];if(f){$('#quizFileLabel').textContent=f.name;$('#quizFileHint').textContent=`${(f.size/1024/1024).toFixed(2)} MB • siap dipakai untuk membuat kuis`;}else{$('#quizFileLabel').textContent='Pilih materi untuk kuis';$('#quizFileHint').textContent='PDF, DOCX, TXT, MD • maksimal 50 MB';}});
const quizDrop=$('#quizDrop');
quizDrop?.addEventListener('dragover',e=>{e.preventDefault();quizDrop.classList.add('dragging')});
quizDrop?.addEventListener('dragleave',()=>quizDrop.classList.remove('dragging'));
quizDrop?.addEventListener('drop',e=>{e.preventDefault();quizDrop.classList.remove('dragging');if(e.dataTransfer.files.length){try{const dt=new DataTransfer();dt.items.add(e.dataTransfer.files[0]);quizFile.files=dt.files;quizFile.dispatchEvent(new Event('change',{bubbles:true}));}catch{$('#quizSetupMsg').textContent='Browser tidak mendukung drag & drop file ini. Klik area upload untuk memilih file.';}}});
$('#quizGenerate').onclick=async()=>{const file=quizFile?.files?.[0];if(!file){$('#quizSetupMsg').textContent='Upload materi dulu dengan klik area upload atau drag & drop file.';return}if(file.size>50*1024*1024){$('#quizSetupMsg').textContent='Ukuran file maksimal 50 MB.';return}try{$('#quizSetupMsg').textContent='Membaca materi dan membuat soal...';const source=await extract(file);const d=await api('/api/quiz/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceText:source,sourceTitle:file.name,count:$('#quizCount').value,type:$('#quizType').value,difficulty:$('#quizDifficulty').value})});state.quiz=d;$('#quizSetup').classList.add('hidden');$('#quizGame').classList.remove('hidden');renderQuiz(d);toast(`Kuis jadi • ${d.provider==='gemini'?'Gemini backup':'AI utama'}`,'good')}catch(e){$('#quizSetupMsg').textContent=e.message}};
function renderQuiz(q){const x=q.question;if(!x){$('#quizGame').innerHTML=`<div class="quiz-card"><h2>🎉 Kuis selesai!</h2><p>Skor: ${q.score}/${q.total}</p><button class="primary" onclick="resetQuiz()">Buat kuis baru</button></div>`;return}const pct=((q.current)/q.total)*100;let answerHtml='';if(x.type==='essay')answerHtml='<textarea id="essayAnswer" class="essay-answer" placeholder="Tulis jawabanmu..."></textarea><button class="primary" id="sendEssay">Jawab</button>';else answerHtml=`<div class="options">${x.options.map(o=>`<button class="option" data-answer="${esc(o.label)}">${esc(o.label)}. ${esc(o.text)}</button>`).join('')}</div>`;$('#quizGame').innerHTML=`<div class="quiz-card"><div class="progress"><i style="width:${Math.max(4,pct)}%"></i></div><div class="q-meta"><span>Soal ${x.number} dari ${x.total}</span><span>Skor ${q.score}</span></div><div class="q-text">${esc(x.question)}</div>${answerHtml}<div id="feedback"></div></div>`;$$('.option').forEach(b=>b.onclick=()=>answerQuiz(b.dataset.answer));$('#sendEssay')?.addEventListener('click',()=>answerQuiz($('#essayAnswer').value))}
async function answerQuiz(answer){try{$$('.option').forEach(b=>b.disabled=true);const d=await api(`/api/quiz/${state.quiz.quizId}/answer`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answer})});state.quiz={...state.quiz,...d,current:d.next?d.next.number-1:state.quiz.total};const f=$('#feedback');f.className=`feedback ${d.correct?'good':'bad'}`;f.innerHTML=`${esc(d.message)}<br><small>${esc(d.explanation||'')}</small>${d.correct&&!d.completed?'':' '}`;if(d.completed){state.quiz={...state.quiz,score:d.score,current:d.total};setTimeout(()=>renderQuiz(state.quiz),1000)}else if(d.correct){setTimeout(()=>renderQuiz({...state.quiz,question:d.next,score:d.score,current:d.next.number-1}),900)}else{$$('.option').forEach(b=>b.disabled=false);const inp=$('#essayAnswer');if(inp)inp.value=''}}catch(e){toast(e.message,'bad');$$('.option').forEach(b=>b.disabled=false)}}
function resetQuiz(){$('#quizSetup').classList.remove('hidden');$('#quizGame').classList.add('hidden');state.quiz=null}
async function loadVault(){try{state.vault=(await api('/api/vault')).items;renderVault()}catch{}}
function renderVault(){const q=$('#vaultSearch').value.toLowerCase();const subj=$('#vaultSubject').value;const items=state.vault.filter(x=>(!q||`${x.title} ${x.subject} ${x.content}`.toLowerCase().includes(q))&&(!subj||x.subject===subj));const subjects=[...new Set(state.vault.map(x=>x.subject).filter(Boolean))];$('#vaultSubject').innerHTML='<option value="">Semua mapel</option>'+subjects.map(x=>`<option ${x===subj?'selected':''}>${esc(x)}</option>`).join('');$('#vaultList').innerHTML=items.length?items.map(x=>`<article class="vault-item"><span class="pill">${esc(x.subject||'UMUM')}</span><h3>${esc(x.title)}</h3><p>${esc(x.content||'File tersimpan tanpa teks.')}</p>${x.attachment?.name?`<small>📎 ${esc(x.attachment.name)}</small>`:''}<div class="vault-actions"><button onclick="openVault('${x.id}')">Edit</button><button onclick="deleteVault('${x.id}')">Hapus</button></div></article>`).join(''):'<div class="vault-item"><h3>Vault masih kosong</h3><p>Upload PDF/DOCX/TXT/MD atau ketik materi sendiri.</p></div>'}
$('#vaultSearch').oninput=renderVault;$('#vaultSubject').onchange=renderVault;$('#addVault').onclick=()=>openVault();
function openVault(id){const x=state.vault.find(a=>a.id===id);$('#vaultId').value=x?.id||'';$('#vaultTitle').value=x?.title||'';$('#vaultSubjectInput').value=x?.subject||'';$('#vaultContent').value=x?.content||'';$('#vaultModalTitle').textContent=x?'Edit materi':'Tambah materi';$('#vaultModal').classList.remove('hidden')}
window.openVault=openVault;window.deleteVault=async id=>{if(!confirm('Hapus materi ini?'))return;try{await api(`/api/vault/${id}`,{method:'DELETE'});toast('Materi dihapus','good');loadVault();loadDashboard()}catch(e){toast(e.message,'bad')}};
$('#vaultClose').onclick=()=>$('#vaultModal').classList.add('hidden');$('#vaultModal').onclick=e=>{if(e.target.id==='vaultModal')$('#vaultModal').classList.add('hidden')};
$('#vaultForm').onsubmit=async e=>{e.preventDefault();try{const fd=new FormData();fd.append('title',$('#vaultTitle').value);fd.append('subject',$('#vaultSubjectInput').value);fd.append('content',$('#vaultContent').value);if($('#vaultFile').files[0])fd.append('file',$('#vaultFile').files[0]);const id=$('#vaultId').value;await api(id?`/api/vault/${id}`:'/api/vault',{method:id?'PUT':'POST',body:fd});$('#vaultModal').classList.add('hidden');toast('Materi tersimpan','good');loadVault();loadDashboard()}catch(e){toast(e.message,'bad')}};
async function loadStreak(){try{const d=await api('/api/streak');const set=new Set(d.dates);let arr=[];for(let i=13;i>=0;i--){const x=new Date();x.setDate(x.getDate()-i);const k=x.toISOString().slice(0,10);arr.push(`<div class="day ${set.has(k)?'on':''}">${x.toLocaleDateString('id-ID',{weekday:'short'})}<br><b>${x.getDate()}</b></div>`)}$('#streakDays').innerHTML=arr.join('')}catch{}}
$('#checkin').onclick=async()=>{try{await api('/api/streak/checkin',{method:'POST'});toast('Check-in berhasil. Semangat belajar! 🔥','good');loadDashboard()}catch(e){toast(e.message,'bad')}};
async function saveProfile(extra={},show=true){const fd=new FormData();fd.append('name',$('#profileName').value||state.user.name);fd.append('email',$('#profileEmail').value||'');fd.append('bio',$('#profileBio').value||'');fd.append('theme',extra.theme||$('#profileTheme').value||state.user.theme||'light');if($('#avatarInput').files[0])fd.append('avatar',$('#avatarInput').files[0]);try{const d=await api('/api/profile',{method:'PUT',body:fd});state.user=d.user;applyTheme(d.user.theme);renderUser();if(show)toast('Profile tersimpan','good')}catch(e){if(show)toast(e.message,'bad')}}
async function profileSubmit(e){e.preventDefault();await saveProfile()};$('#profileForm').onsubmit=profileSubmit;$('#profileTheme').onchange=()=>applyTheme($('#profileTheme').value);$('#avatarInput').onchange=()=>{const f=$('#avatarInput').files[0];if(f){const u=URL.createObjectURL(f);$('#profileAvatar').innerHTML=`<img src="${u}">`;$('#avatarBtn').innerHTML=`<img src="${u}">`}};
$$('.copy-contact').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);toast('Kontak berhasil disalin','good')}catch{toast('Tidak bisa menyalin kontak','bad')}});
$('#passwordForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/profile/password',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({oldPassword:$('#oldPassword').value,newPassword:$('#newPassword').value})});e.target.reset();toast('Password berhasil diubah','good')}catch(e){toast(e.message,'bad')}};
window.showPage=showPage;window.resetQuiz=resetQuiz;boot();
